# Generated by Django 4.2.5 on 2023-11-10 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorPool', '0002_alter_pick_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 17, 4, 2, 852290), verbose_name='date published'),
        ),
    ]
