# Generated by Django 4.2.5 on 2023-11-28 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorPool', '0003_alter_pick_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='is_win',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 15, 51, 15, 634118), verbose_name='date published'),
        ),
    ]
