# Generated by Django 4.2.5 on 2024-10-11 20:47

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survivorPool', '0004_pick_is_win_alter_pick_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 11, 16, 47, 59, 102126), verbose_name='date published'),
        ),
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together={('team', 'user_name', 'week')},
        ),
    ]
