# Generated by Django 4.2.5 on 2024-10-11 20:49

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survivorPool', '0005_alter_pick_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together={('user_name', 'week')},
        ),
        migrations.AlterField(
            model_name='pick',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 11, 16, 49, 38, 144790), verbose_name='date published'),
        ),
    ]
