# Generated by Django 5.2.7 on 2025-10-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorPool', '0007_alter_pick_is_win_alter_pick_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='is_win',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
