# Generated by Django 5.2.7 on 2025-10-11 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorPool', '0008_alter_pick_is_win'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, unique=True)),
                ('week', models.IntegerField()),
                ('commence_time', models.DateTimeField()),
                ('spread', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('moneyline_home', models.IntegerField(blank=True, null=True)),
                ('moneyline_away', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='survivorPool.team')),
                ('favorite_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favored_games', to='survivorPool.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='survivorPool.team')),
            ],
            options={
                'ordering': ['week', 'commence_time'],
                'unique_together': {('week', 'home_team', 'away_team')},
            },
        ),
    ]
