# Generated by Django 5.2.7 on 2025-10-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorPool', '0008_alter_pick_is_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='current_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='game_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_home',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='moneyline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='opponent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='spread',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
