# Generated by Django 5.2.7 on 2026-09-13 17:00

from django.db import migrations, models


SEQUENCE_RENAMES = (
    ("survivorPool_game_id_seq", "survivorpool_game_id_seq"),
    ("survivorPool_weeklockrun_id_seq", "survivorpool_weeklockrun_id_seq"),
    ("survivorPool_chatmessage_id_seq", "survivorpool_chatmessage_id_seq"),
    ("survivorPool_seasonsettings_id_seq", "survivorpool_seasonsettings_id_seq"),
)


def rename_identity_sequences(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for old_name, new_name in SEQUENCE_RENAMES:
            cursor.execute(
                f'ALTER SEQUENCE "{old_name}" RENAME TO "{new_name}"'
            )


def restore_identity_sequence_names(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for old_name, new_name in reversed(SEQUENCE_RENAMES):
            cursor.execute(
                f'ALTER SEQUENCE "{new_name}" RENAME TO "{old_name}"'
            )


class Migration(migrations.Migration):

    dependencies = [
        ('survivorPool', '0014_alter_chatmessage_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='missed_deadline',
            field=models.BooleanField(db_default=False, default=False, help_text='Auto-assigned loss when no pick was made before the final weekly kickoff.'),
        ),
        migrations.RunPython(
            rename_identity_sequences,
            reverse_code=restore_identity_sequence_names,
        ),
    ]
